---
version: "3.8"
services:
  db:
    image: postgres:15.1
    container_name: messenger-db
    restart: always
    environment: # Use postgres example user/password credentials
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: messenger_dev
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
    networks:
      - mm_2023
networks:
  mm_2023:
    name: mm_2023
    driver: bridge
volumes:
  db-data:
